{% set name = "indizio-dev" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/aaronmussig/indizio.git
  git_depth: 1

build:
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - dash
    - dash_bootstrap_components
    - dash_cytoscape
    - diskcache
    - dash_bio
    - pydantic
    - networkx
    - orjson
    - dendropy
    - frozendict
    - pillow
    - pandas
    - numpy

test:
  imports:
    - indizio
