{% set name = "indizio-dev" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: git@github.com:aaronmussig/Indizio.git

build:
  noarch: python
  number: 0
  entry_points:
    - indizio = indizio.__main__:main
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vvv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8.0
    - dash >=2.14.0
    - dash-bootstrap-components >=1.5.0
    - dash_cytoscape >=0.2.0
    - diskcache >=5.2.1
    - multiprocess >=0.70.12
    - psutil >=5.8.0
    - dash-bio
    - pydantic >=2.5.0
    - networkx
    - orjson
    - dendropy
    - frozendict
    - pillow
    - pandas
    - numpy
    - tqdm
    - scipy <1.12.0
    - phylodm >=3.0.0

# Needs scipy <1.12.0 as plotly dendrogram doesn't support higher versions

#test:
#  imports:
#    - indizio
