{% set name = "indizio" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3e01465ec2a3b8425495ab8c0739fb9030cf91683db6e44b5127a04775d186eb

build:
  noarch: python
  number: 1

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - biolib >=0.1.0
    - numpy >=1.8.0
    - future
    - dendropy
    - blast
    - hmmer ==3.1b2

test:
  imports:
    - genometk
  commands:
    - genometk -h

about:
  home: https://github.com/dparks1134/GenomeTk
  summary: 'The genome toolkit is a collection of methods for determining characteristics about genomes.'