name: Publish to PyPI

on:
  release:
    types: [ released ]

jobs:

  build:
    name: Python build *.tar.gz
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Build
        run: |
          python -m pip install -U pip
          python -m pip install -U build setuptools wheel
          python -m build --sdist --wheel

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: indizio-build
          path: dist
          retention-days: 1

  publish:
    name: Publish to test PyPI
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/indizio
    permissions:
      id-token: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: indizio-build
          path: dist/

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
